plugins {
    id 'application'
}

group = rootProject.maven_group
version = rootProject.mod_version

application {
    mainClass = 'com.spaceclient.launcher.LauncherMain'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
